---
- hosts: srv
  remote_user: root

  tasks:
- name: install system updates for ubuntu systems
  apt: upgrade=dist update_cache=yes
  when: ansible_distribution == "Ubuntu"
  
- name: Install basic packages
  apt: name={{ item }} state=installed
  with_items:
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - supervisor
    - python-pip
    - python3-pip
    - python
    - php
    - wget

    
