---
- hosts: srv
  remote_user: root
  become: yes
  tasks:
    - name: Install packages
      apt: name= state=present
      with_items:
          - git-core
          - vim
          - python-pip
          - python-virtualenv
          - wget
          - git
          - php

    
