---
- hosts: webservers
  remote_user: root
  vars:
    http_port: 80
    doc_dir: /ansible/
    doc_root: /var/www/html/
    max_clients: 5

  tasks:
  - name: Ensure that Apache is installed
    apt: name=apache2 state=present
    when: ansible_os_family == "Ubuntu"

  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started
    
